# This is a full example of how to run the echo messaging actor connected to NATS, listening on `wasmcloud.echo`
# This example requires you to have WADM running: https://github.com/wasmCloud/wadm/. You
# can deploy this example with a simple command:
#
# `wash app deploy wadm.yaml`

apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: echo-httpserver
  annotations:
    version: v0.0.1
    description: "wasmCloud Echo httpserver Example"
spec:
  components:
    - name: echo httpserver
      type: actor
      properties:
        image: wasmcloud.azurecr.io/echo_httpserver:0.1.7
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
        - type: linkdef
          properties:
            target: httpserver
            values:
              SUBSCRIPTION: wasmcloud.echo

    - name: httpserver
      type: capability
      properties:
        image: wasmcloud.azurecr.io/httpserver:0.19.1
        contract: wasmcloud:httpserver
